---
title: "Study_Map"
author: "Tali Caspi"
date: "2025-12-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse); library(ggmap); library(ggspatial)
```

### **Load and Merge Data**

Load all trial data, remove foxes, remove Lake Chabot, and trials with no recorded data. Then select only relevant columns for making the map, keep only one row for each location, and merge to coordinate data.

```{r}
# load and filter trial data
data_all <- read.csv("Data/Q1_Summary_All_Anonymized.csv") %>% 
  filter(Species != "Gray Fox" & Species != "Red Fox") %>%   # remove foxes
  filter(Location != "Lake Chabot Dumpster") %>% # remove Lake Chabot
  filter(is.na(Dummy)) %>%  # remove trials with no recorded data
  select(c(Location, Home, FinalSolverofLocation)) %>% 
  distinct()

length(unique(data_all$Location)) # 110 locations

# load location data
locations <- read.csv("Data/StantonPuzzleStudyLocations_Anonymized.csv")

# join data frame
data_locs <- left_join(data_all, locations, by="Location") %>% 
  mutate(Solved = FinalSolverofLocation != "None")
```

### Make Study Map

```{r}
# make map
bbox <- c(left = -122.45, right = -122.02, bottom = 37.69, top = 38.05)

map <- get_stadiamap(bbox, zoom = 12, maptype = "stamen_terrain", scale=2)
  
map %>% ggmap()+
  geom_point(data = data_locs, aes(x=Long, y=Lat, fill=Solved),
             shape=23, size=3, alpha=0.8)+
  scale_fill_manual(values=c("grey25", "coral"), labels=(c("Unsolved", "Solved")))+
  
  theme_minimal()+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill = "white", color="white"),
        legend.box.background = element_rect(fill = "white", color = "white"),
        plot.background  = element_rect(fill = "white",color=NA),
        panel.background = element_rect(fill = "white", color=NA))+
  
  annotation_scale(location = "bl", width_hint = 0.2) + 
  coord_sf(crs = 4326)

ggsave("Figures/PuzzleMap.png", dpi=600, height=6, width=5)
```

Create Inset:

```{r}
library(usmap)

# Define counties to highlight
highlight_counties <- c("Contra Costa County", "Alameda County")

# Get county-level data for California
county_data <- us_map(regions = "counties") %>%
  filter(full == "California") %>%
  mutate(fill_color = ifelse(county %in% highlight_counties, "coral", "#595959"))


ggplot() +
  geom_sf(data = county_data, aes(fill = fill_color), color = NA) +  # Remove county borders
  scale_fill_identity() +  # Use predefined colors directly
  theme_void() +  # Completely removes background elements
  theme(panel.background = element_rect(fill = "#CCD9E6", color = NA))

ggsave("Figures/CA.png", dpi=600)
```
